import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, readFile, writeFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { gunzipSync } from 'node:zlib';
import { spawnSync } from 'node:child_process';
import { sha256 } from '../src/benchmark/prompts.mjs';
import { templateCitationFiles } from '../src/benchmark/study.mjs';
import { projectFiles } from '../src/benchmark/export.mjs';
import { readExportedProject } from '../src/benchmark/exported-project.mjs';

const archive = await readFile(new URL('./fixtures/standalone-0.1.0.json.gz', import.meta.url));
const receipt = JSON.parse(await readFile(new URL('./fixtures/standalone-0.1.0.json', import.meta.url), 'utf8'));
const files = JSON.parse(gunzipSync(archive));

test('0.1.0 study remains intact and retains its original template citations', async () => {
  assert.equal(await sha256(archive), receipt.archiveSha256);
  const inspected = await readExportedProject(files);
  assert.equal(inspected.integrity.ok, true);
  assert.equal(inspected.project.sha256, receipt.projectSha256);
  assert.deepEqual(inspected.project.spec.generator, receipt.generator);
  for (const [name, contents] of Object.entries(await templateCitationFiles(inspected.project))) {
    assert.equal(contents, files[name], 'historical citation changed: ' + name);
  }
});

test('0.1.0 pinned CLI verifies, regenerates identical reports and resumes without recollection', async t => {
  const root = await mkdtemp(join(tmpdir(), 'benchmark-legacy-'));
  t.after(() => rm(root, { recursive: true, force: true }));
  for (const [name, contents] of Object.entries(files)) {
    await mkdir(dirname(join(root, name)), { recursive: true });
    await writeFile(join(root, name), contents);
  }
  for (const command of ['verify', 'analyze', 'run']) {
    const result = spawnSync(process.execPath, ['cli.mjs', command], { cwd: root, encoding: 'utf8', timeout: 20000 });
    assert.equal(result.status, 0, command + '\n' + result.stdout + result.stderr);
  }
  for (const name of ['results/attempts.jsonl', 'results/report.html', 'results/report.md', 'results/summary.json', 'CITATION.cff', 'CITATION.bib']) {
    assert.equal(await readFile(join(root, name), 'utf8'), files[name], 'pinned artifact changed: ' + name);
  }
});

test('re-exported 0.1.0 metadata keeps the same generator and template as its citations', async () => {
  const { project } = await readExportedProject(files);
  const exported = await projectFiles(project, files);
  const metadata = JSON.parse(exported['package.json']).toolsenabled;
  assert.equal(metadata.generator, 'ToolsEnabled BenchMark Builder 0.1.0');
  assert.equal(metadata.template, 'research-benchmark-template 2.1.0');
  assert.match(exported['README.md'], /Generated by ToolsEnabled BenchMark Builder 0\.1\.0/);
  assert.equal(exported['CITATION.cff'], files['CITATION.cff']);
});

test('an explicit new draft from a 0.1.0 study records the current generator when frozen', async () => {
  const { newExperimentDraft } = await import('../src/benchmark/starters.mjs');
  const { RUNTIME_FILES, GENERATOR, bindRuntimeSources, freezeStudy } = await import('../src/benchmark/study.mjs');
  const original = JSON.parse(files['project.json']);
  const draft = newExperimentDraft(original.spec, { purpose: 'recorded-diagnostic' });
  const sources = Object.fromEntries(await Promise.all(RUNTIME_FILES.map(async name =>
    [name, await readFile(new URL('../src/benchmark/' + name, import.meta.url), 'utf8')])));
  const replacement = await freezeStudy(await bindRuntimeSources(draft, sources));
  assert.deepEqual(replacement.spec.generator, GENERATOR);
  assert.notEqual(replacement.sha256, original.sha256);
  assert.deepEqual(original.spec.generator, receipt.generator);
  assert.equal(original.sha256, receipt.projectSha256);
});
