import { build } from "esbuild";
import { bundleMcp } from "./mcp-bundle.mjs";
import { readFile, writeFile, mkdir, copyFile, rm } from "node:fs/promises";
import { dirname, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { bundlePlugins } from "./plugin-bundle.mjs";
import { CORE_RUNTIME_FILES } from "../src/benchmark/study-schema.mjs";
const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
process.chdir(root);
const { version } = JSON.parse(await readFile("package.json", "utf8"));
await bundleMcp(root);
const configured = JSON.parse(await readFile("plugins.json", "utf8"));
const plugins = Array.isArray(configured) ? { extensions: configured, runtime: [] } : configured;
if (!plugins || !Array.isArray(plugins.extensions) || !Array.isArray(plugins.runtime))
  throw new Error("plugins.json needs extensions and runtime arrays.");
const pluginFiles = plugins.runtime.flatMap(entry => {
  if (!Array.isArray(entry.files) || !entry.files.includes(entry.module)) throw new Error("A runtime plugin must inventory its entry module and dependencies.");
  return entry.files;
}).sort();
const inventory = [...CORE_RUNTIME_FILES, ...pluginFiles];
if (inventory.some(name => typeof name !== 'string' || !/^[a-zA-Z0-9_-]+\.(mjs|py)$/.test(name)) || new Set(inventory.map(name => name.toLowerCase())).size !== inventory.length)
  throw new Error("Runtime plugin inventories must use unique local module filenames without core collisions.");
for (const name of inventory) await readFile(resolve(root, 'src/benchmark', name));
await writeFile('src/benchmark/runtime-inventory.mjs', '// Generated from plugins.json by tools/build.mjs. Data only; no registration side effects.\nexport const PLUGIN_RUNTIME_FILES = Object.freeze(' + JSON.stringify(pluginFiles) + ');\n');
const { source } = await bundlePlugins({ root, entries: plugins.extensions, runtimeEntries: plugins.runtime, externalRuntimeFiles: inventory });
await writeFile("src/benchmark/plugins.mjs", source);
const rawImports = inventory.map((name, index) => `import runtime${index} from './benchmark/${name}?raw';`).join('\n');
const rawEntries = inventory.map((name, index) => `${JSON.stringify(name)}: runtime${index}`).join(', ');
await writeFile('src/research-benchmark-sources.js', '// Generated by tools/build.mjs from the configured runtime inventory.\n' + rawImports + '\nexport const sources = { ' + rawEntries + ' };\n');
await rm(resolve(root, "dist"), { recursive: true, force: true });
await mkdir("dist", { recursive: true });
await build({
  entryPoints: ["src/app/main.js"],
  bundle: true,
  splitting: true,
  outdir: "dist/assets",
  format: "esm",
  platform: "browser",
  target: "es2022",
  minify: true,
  define: { __BENCH_VERSION__: JSON.stringify(version) },
  metafile: true,
  logLevel: "info",
  plugins: [
    {
      name: "raw-runtime",
      setup(b) {
        b.onResolve({ filter: /\?raw$/ }, (a) => ({
          // esbuild includes namespace module identities in chunk hashes even
          // when the emitted text is identical. Keep raw IDs checkout-relative.
          path: relative(root, resolve(dirname(a.importer), a.path.slice(0, -4))).split(sep).join('/'),
          namespace: "raw",
        }));
        b.onLoad({ filter: /.*/, namespace: "raw" }, async (a) => ({
          contents: await readFile(resolve(root, a.path), "utf8"),
          loader: "text",
        }));
      },
    },
  ],
});
await copyFile("index.html", "dist/index.html");
await copyFile("src/app/favicon.svg", "dist/favicon.svg");
console.log("Built ToolsEnabled BenchMark Builder " + version);
